### ISSUE TITLE
什么问题  如何纠正？

### ISSUE THREAD

**Issue by jack00000** [sxei/myqq#1]
![2017-12-11_203545](https://user-images.githubusercontent.com/18373908/33831394-e74e0f54-deb2-11e7-9eee-011b702229ec.png)

**Comment by sxei** [comment]
不会吧，是GitHub的代码还是CSDN那个版本？这个问题以前存在，我记得我修复过了，看看控制台日志错误

**Comment by jack00000** [comment]
github上的   没有报错提示。  

![2017-12-13_133630](https://user-images.githubusercontent.com/18373908/33923277-349de208-e00b-11e7-97b6-df634d5bbe91.png)

**Comment by sxei** [comment]
![qq 20171213160532](https://user-images.githubusercontent.com/9378372/33928096-9fc9eb80-e01f-11e7-8a86-93a67072eb59.png)
我刚刚试了一遍，没问题哦

**Comment by sxei** [comment]
![image](https://user-images.githubusercontent.com/9378372/33928241-4723bc76-e020-11e7-81f5-738f25d09af3.png)
不知道为啥你这里没有收到好友列表信息

**Comment by jack00000** [comment]
找到问题啦，注册用户时不规范（有些没填或乱填）导致获取数据库的用户表失败。。。。
![2017-12-13_195322](https://user-images.githubusercontent.com/18373908/33937802-d49dd19e-e03f-11e7-8265-5cb7cc86aca3.png)

**Comment by sxei** [comment]
哈哈，好吧，找到原因就好，这个是当初在学校的小项目，有很多问题。
